#web: gunicorn service:app
#web: uvicorn service:app --host=0.0.0.0 --port=${PORT:-5000}
release: alembic revision -m "New Migration" && alembic upgrade head
web: gunicorn service:app -k uvicorn.workers.UvicornWorker
